# Heavily inspired by Oliver Grisel's appveyor-demo (https://github.com/ogrisel/python-appveyor-demo)
version: '{branch}-{build}'

# Only test master and pull requests; skip tags.
# Other branches can allow themselves.
branches:
  only:
    - master
skip_branch_with_pr: false
skip_tags: false

cache:
  - '%LOCALAPPDATA%\pip\Cache'

# Match travis
clone_depth: 50

environment:
  matrix:
    - PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python34"

install:
  # Ensure we use the right python version
  - "SET PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip --version"
  - "pip install --upgrade pip setuptools pymssql ppu"

# No build step
build: false

test_script:
  - "python test-pymssql-at-appveyor.py"

after_test:
  - remove-old-files.py -o 180 %LOCALAPPDATA%\\pip\\Cache
